-- Auto-generated by AllIN1Tool.lua
-- Timestamp: 32253
local cfg = {
  VBAT = "Vbat",
  VBEC = "Vbec",
  CURR = "Curr",
  RPM = "Hspd",
  RSSI = "RSSI",
  TFBL = "Tfbl",
  TESC = "Tesc",
  CONS = "mah1",
  VFR = "VFR",
  CHP = "ChP",
}

return cfg
